language: r
cache: packages
latex: false

# Note: http test servers are flaky and we want to minimze false positives
# so we skip examples and vignettes (but not unit tests) on OS X.

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew reinstall curl --with-nghttp2 --HEAD
        - brew link --force curl
    - os: osx
      osx_image: xcode7.3
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
